name: test_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - dask
  - zarr
  - xarray>=2024.10.0
  - h5netcdf
  - h5py
  - pandas
  - cfgrib
  - cftime
  # Temporary workaround for #508
  - eccodes <2.38

  - astropy
  - requests
  - aiohttp
  - pytest-cov
  - pytest-subtests
  - fsspec<=2024.12.0
  - dask
  - scipy
  - s3fs
  - gcsfs
  - python-blosc
  - flake8
  - black
  - fastparquet
  - pip
  - pyopenssl
  - tifffile
  - netCDF4
#  - pip:
#      - git+https://github.com/fsspec/filesystem_spec
#      - ipfsspec
