name: test_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - dask
  - zarr
  - xarray>=2024.10.0
  - h5netcdf
  - h5py
  - pandas
  - cfgrib
  # Temporary workaround for #508
  - eccodes <2.38

  - cftime
  - astropy
  - requests
  - aiohttp
  - pytest-cov
  - fsspec
  - gcsfs
  - dask
  - scipy
  - s3fs
  - python-blosc
  - flake8
  - fastparquet
  - pyopenssl
  - black
  - pip
  - tifffile
  - rioxarray
  - netCDF4
#  - pip:
#      - git+https://github.com/fsspec/filesystem_spec
