name: test_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - dask
  - zarr>=3.0.1
  - xarray>=2024.10.0
  - h5netcdf
  - h5py
  - pandas
  - cfgrib
  # Temporary workaround for #508
  - eccodes <2.38
  - ujson
  - cftime
  - astropy
  - requests
  - aiohttp
  - pytest-cov
  - pytest-subtests
  - pytest-timeout
  - dask
  - scipy
  - s3fs
  - gcsfs
  - python-blosc
  - flake8
  - fastparquet
  - pyopenssl
  - black
  - pip
  - tifffile
  - rioxarray
  - netCDF4
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
