name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - zarr
  - xarray
  - h5netcdf
  - h5py
  - pandas
  - cfgrib
  - cftime
  - astropy
  - requests
  - aiohttp
  - pytest-cov
  - fsspec
  - dask
  - scipy
  - s3fs
  - python-blosc
  - flake8
  - black
  - fastparquet
  - pip
  - pyopenssl
  - tifffile
  - netCDF4
  - sphinx
  - numpydoc
  - sphinx-rtd-theme
  - ujson
